#!/usr/bin/env node
/**
 * One-time script to download 3 months of LTC/USDT 1-minute close prices
 * from Binance public API and write src/data/ltcPriceHistory.ts
 *
 * Usage: node scripts/downloadLtcHistory.mjs
 */

import { writeFileSync, appendFileSync, rmSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SYMBOL = 'LTCUSDT';
const INTERVAL = '1m';
const LIMIT = 1000; // max per Binance request
const MONTHS = 3;
const TOTAL_MINUTES = MONTHS * 30 * 24 * 60; // 129,600
const DELAY_MS = 250; // between requests to respect rate limits

const endTime = Date.now();
const startTime = endTime - TOTAL_MINUTES * 60 * 1000;

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function fetchKlines(start, end) {
  const url = `https://api.binance.com/api/v3/klines?symbol=${SYMBOL}&interval=${INTERVAL}&limit=${LIMIT}&startTime=${start}&endTime=${end}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Binance API error ${res.status}: ${await res.text()}`);
  return res.json();
}

async function main() {
  const prices = [];
  let cursor = startTime;
  let batch = 0;

  console.log(`Downloading ${TOTAL_MINUTES} minutes of LTC/USDT data...`);
  console.log(`From: ${new Date(startTime).toISOString()}`);
  console.log(`To:   ${new Date(endTime).toISOString()}`);
  console.log('');

  while (cursor < endTime) {
    const batchEnd = Math.min(cursor + LIMIT * 60 * 1000, endTime);
    const klines = await fetchKlines(cursor, batchEnd);

    if (klines.length === 0) break;

    // Binance kline format: [openTime, open, high, low, close, ...]
    for (const k of klines) {
      prices.push(parseFloat(k[4])); // close price
    }

    // Advance cursor to after the last candle
    cursor = klines[klines.length - 1][0] + 60 * 1000;
    batch++;

    process.stdout.write(`\rBatch ${batch}: ${prices.length} points fetched...`);

    if (cursor < endTime) await sleep(DELAY_MS);
  }

  console.log(`\n\nDone! Total points: ${prices.length}`);
  const minPrice = prices.reduce((a, b) => a < b ? a : b, Infinity);
  const maxPrice = prices.reduce((a, b) => a > b ? a : b, -Infinity);
  console.log(`Min price: $${minPrice.toFixed(4)}`);
  console.log(`Max price: $${maxPrice.toFixed(4)}`);

  const outPath = join(__dirname, '../src/data/ltcPriceHistory.ts');
  if (existsSync(outPath)) rmSync(outPath);

  const header = `// Auto-generated by scripts/downloadLtcHistory.mjs — do not edit manually.
// Source: Binance public API — LTCUSDT 1m close prices, 3 months
// Generated: ${new Date().toISOString()}
// Total points: ${prices.length}
export const LTC_PRICE_HISTORY: number[] = [\n`;

  writeFileSync(outPath, header, 'utf8');

  // Write in chunks of 5000 to avoid call stack issues
  const CHUNK = 5000;
  for (let i = 0; i < prices.length; i += CHUNK) {
    const slice = prices.slice(i, i + CHUNK);
    appendFileSync(outPath, '  ' + slice.join(',\n  ') + ',\n', 'utf8');
  }

  appendFileSync(outPath, '];\n', 'utf8');
  console.log(`\nWritten to: ${outPath}`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
